### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by avantgardnerio** [softdev87/rust_rtsp_server#3]
Thanks for making this! I tried to use gstreamer's RTSP server and ran into issues with it not accepting the OPTION verb, whereas your project seems to work out of the box. 

One request: without a license file, it's unclear what the project can be used for. When you have a moment, could you add a license file?

Thanks,

- Brent

**Comment by softdev87** [comment]
I've added an MIT license there now #4 

Are you crafting the `RTSP` messages with a custom piece of code ? 
It might be possible that there is some constraint that my code here is not checking, but I've found [gst-rtsp-server](https://gitlab.freedesktop.org/gstreamer/gst-rtsp-server/-/blob/master/examples/test-launch.c) to work nicely actually.
